---
- hosts: all
  remote_user: root

  tasks:
    - name: install httpd
      yum: 
        name: httpd
        state: latest
    - name: file
      file:

...

- 代表引导一个列表（数组）,同级表示数组同级。
   其中tasks又是另一个了列表（数组）
所以一个play就是一个数组
- hosts: 
  remote_user: root
  tasks:
    - name: install package
      yum:
        name: httpd
        state: latest
    - name: copy
      src: /etc/aaa
      dest: /etc/bbb